server:
  port: 8080

logging:
  level:
    root: info
    org.springframework.boot: info
    org.springframework.cloud: info
    org.springframework.cloud.gateway.handler: debug
    org.springframework.cloud.gateway.route: debug

spring:
  application:
    name: "ms-gateway"
  cloud:
    gateway:
      routes:
        - id: ms-one
          uri: ${GET_ROUTE_URI:http://localhost:8081}
          predicates:
            - Path=/countries/**
          filters:
            - PrefixPath=/ms-one
            - AddResponseHeader=X-Powered-By,MS-Gateway
        - id: ms-two
          uri: ${GET_ROUTE_URI:http://localhost:8082}
          predicates:
            - Path=/airports/**
          filters:
            - PrefixPath=/ms-two
            - AddResponseHeader=X-Powered-By,MS-Gateway
